### ISSUE TITLE
IFD of Mask data handling in COG Data

### ISSUE THREAD

**Issue by gcebelieu** [opengeospatial/CloudOptimizedGeoTIFF#25]
(This issue comes from DGIWG Imagery and Gridded Data Panel review of COG Draft Standard - September 2022)

The "Requirement 3" clauses ("/req/req-class-geotiff-overviews/overviews") seems to imply that an IFD that is related to a full resolution data image SHALL point to a next IFD of a reduced resolution image (if there is any) in the COG File otherwise it should point to nothing. 

If this is really the case (if we have well understood), if a COG file is also shipping a transparency mask image data along with the image data itself, how can the IFD related to the mask image data be reached? In other words where can the pointer to this IFD be placed?

**Comment by joanma747** [comment]
Actually, you are right. The requirement was involuntarily written an a way that prevented more than image (or a mask) in the TIFF file. The language of requirement 3 is particularly complicated due to several possible alternatives. This has been fixed and a clarification note has been added.

Thanks for spotting this

**Comment by joanma747** [comment]
No one complained for a while so I'm closing this issue

**Comment by gcebelieu** [comment]
Thank you @joanma747 the proposed rewritting seems to solve this issue that was raised.
