### ISSUE TITLE
Provinding guidances regarding compression capabilities

### ISSUE THREAD

**Issue by gcebelieu** [opengeospatial/CloudOptimizedGeoTIFF#27]
(This issue comes from DGIWG Imagery and Gridded Data Panel review of COG Draft Standard - September 2022)

Recommandation 2 ("/rec/rec-class-geotiff/rec-compression") is stating: "In a COG file, tiled data should be compressed efficiently"

This makes clearly sense but remains very open to interpretation. Maybe this recommendation could be more specific and provide more guidances regarding compressions capabilities.

**Comment by joanma747** [comment]
The recommendation has been changed to: "In a COG file, tiled data should be compressed efficiently using LZW or JPEG compression" that are the two compressions in TIFF v6 that are recommended for imagery (other compressions target facsimile)

**Comment by geospatial-jeff** [comment]
While it is true that LZW and JPEG are the two image compressions mentioned in TIFF v6 there are many other image-based compressions that have become popular since TIFF v6's original release in 1992.  Practically speaking, if this conformance class limits compression to LZW/JPEG then most COGs found in the wild will not be OGC compliant as they often use compressions like ZSTD, DEFLATE, WEBP, LERC, LERC_ZSTD etc.  I have been working with COGs at large scales for many years now and I have personally never created a COG with LZW compression, as other lossless compressions are simply better.  Even binary compressions can be useful for COGs (ex. segmentation masks created by machine learning workflows).  New compressions are constantly being released too so this conformance class as currently written will not age well.

I think this conformance class should include language indicating that modern image compressions not included in the original TIFF v6 specification can be used with a warning that certain compressions may not be supported by specific TIFF readers (although libtiff already supports most of these).  Libtiff should probably be the reference example for what compressions are commonly supported.

See https://www.awaresystems.be/imaging/tiff/tifftags/compression.html for more details.

**Comment by joanma747** [comment]
Thank fr the advice. I have reused most of your text in the recommendation. I believe we can close the issue now.
