### ISSUE TITLE
Overviews or Reduced-Resolution Subfiles?

### ISSUE THREAD

**Issue by jratike80** [opengeospatial/CloudOptimizedGeoTIFF#6]
I guess that term Overview has been used in the beginning of the editing phase but another term has been introduced later:
> This is the reason why this standard favors the use of the expression Reduced-Resolution Subfile instead of overview.

In the standard text "overview(s)" appears 38 times and "reduced" 32 times. If "reduced-resolution subfile" should be favored then maybe it should be used more frequently. But I am not sure how popular the long term will become in everyday speech. I have a feeling that currently in other connections "pyramid layers" still lead and "overviews" come next, and some of us even know the Reduced Resolution Dataset from ERDAS if not else then as an acronym RRD.

**Comment by joanma747** [comment]
That is a good point. I'll correct this aspect in the document. I prefer "Reduced-Resolution Subfile" because this is what the original TIFF specification uses. But it seems that I could not resist the use of "overview".

There is a section in the document template called "overview" so a couple of hits are actually not referring to the same concept 😄

Joan

________________________________
From: Jukka Rahkonen ***@***.***>
Sent: Wednesday, June 1, 2022 15:50
To: opengeospatial/CloudOptimizedGeoTIFF ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [opengeospatial/CloudOptimizedGeoTIFF] Overviews or Reduced-Resolution Subfiles? (Issue #6)


I guess that term Overview has been used in the beginning of the editing phase but another term has been introduced later:

This is the reason why this standard favors the use of the expression Reduced-Resolution Subfile instead of overview.

In the standard text "overview(s)" appears 38 times and "reduced" 32 times. If "reduced-resolution subfile" should be favored then maybe it should be used more frequently. But I am not sure how popular the long term will become in everyday speech. I have a feeling that currently in other connections "pyramid layers" still lead and "overviews" come next, and some of us even know the Reduced Resolution Dataset from ERDAS if not else then as an acronym RRD.
